spring.application.name=atsanalyzer

server.port=8080

# ==========================
# OpenRouter
# ==========================
openrouter.api.key=YOUR_OPENROUTER_API_KEY

# ==========================
# MySQL Configuration
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/resumateai
spring.datasource.username=root
spring.datasource.password=root123

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect